backend:
  name: github
  repo: Siris20/PrimariaEmilianoZapata
  branch: master
  base_url: https://sveltia-cms-auth.22050041.workers.dev
  auth_endpoint: callback

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "avisos"
    label: "Avisos y Noticias del Carrousel"
    label_singular: "Aviso o Noticia"
    files:
      - label: "Noticias del Carrousel"
        name: "noticias"
        file: "data/noticias.json"
        fields:
          - label: "Avisos y Noticias"
            name: "items"
            widget: "list"
            collapsed: false
            summary: "{{fields.titulo}}"
            fields:
              - { label: "Título", name: "titulo", widget: "string", required: true }
              - { label: "Descripción", name: "descripcion", widget: "text", required: true }
              - { label: "Imagen de fondo", name: "imagen", widget: "image", required: true, multiple: false }